version: "2"
networks:
  main:
    external: true
services:
  portainer:
    hostname: portainer
    image: portainer/portainer-ce:lts
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/portainer:/data
    networks:
      main: null
