name: watchtower
networks:
  main:
    external: true
services:
  watchtower:
    container_name: watchtower
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: 0 0 * * *
    image: containrrr/watchtower:latest
    networks:
      main: null
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
