version: "3.8"
networks:
  main:
    external: true

services:
  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    container_name: pufferpanel
    networks:
      - main
    volumes:
      - ${PUFFERPANEL_CONFIG}:/etc/pufferpanel
      - ${PUFFERPANEL_STORAGE_DIR}:/var/lib/pufferpanel
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 5657:5657
      - 25565:25565
    restart: unless-stopped
